### ISSUE TITLE
Package and distribute Dapr-Ambient resoruces

### ISSUE THREAD

**Issue by salaboy** [dapr-sandbox/dapr-shared#20]
- [x] Create a multi-platform Docker container for the init-container
- [x] Helm chart package and host in dapr helm repository
- [ ] Add section into the documentation

**Comment by salaboy** [comment]
@yaron2 we might need help on this.. 
is it possible to add @mcruzdev to the org so he can help with the changes ?

**Comment by asarenkansah** [comment]
I can help to start to do some basic research for this one

**Comment by salaboy** [comment]
@artursouza can you help us with this? any pointers? I would love @asarenkansah and @mcruzdev to be able to work on this

**Comment by asarenkansah** [comment]
Yes I'll need answers to the following questions to get started on this:

- What is the purpose of the init-container? What code will it use and what does it need to accomplish?
- What do you mean by “Helm chart package and host in dapr helm repository”? Are you saying we need to modify an existing helm chart package or create a new one and put it in the dapr helm repo?
- What documentation do all these changes need to be added to?

**Comment by asarenkansah** [comment]
My guess on the answers to the questions go as follows, correct me if any of my assumptions are wrong:

- The code that's used is found [here](https://github.com/dapr-sandbox/dapr-ambient/tree/main/cmd/ambient-init). It is trying to do some type of work in order to allow dapr to leverage the daemonsets?
- The helm chart package is found [here](https://github.com/dapr-sandbox/dapr-ambient/tree/main/chart/dapr-ambient). The deployment file will likely need to be modified to include the init-container
- The readme file will likely need to be changed to include these specs

**Comment by mcruzdev** [comment]
Hi @asarenkansah, how are you?
> What is the purpose of the init-container? What code will it use and what does it need to accomplish?

The purpose of the `init-container` is to setup all necessary configuration for `daprd`.

> What do you mean by “Helm chart package and host in dapr helm repository”? Are you saying we need to modify an existing helm chart package or create a new one and put it in the dapr helm repo?

We need to package our Helm Charts and release it on Helm repository, it allows the user do not worry about package locally the Helm chart and install it. The only thing that the user needs to do is something like it:

```sh
helm add repo ambient https://salaboy.github.io/helm/
helm repo update
helm install my-ambient amabient/dapr-ambient  --set ambient.appId=<DAPR_APP_ID> --set ambient.channelAddress=<REMOTE_URL> --set ambient.daprd.app.port=<REMOTE_PORT>
```

**Comment by asarenkansah** [comment]
Thanks for the explanation, that helps a lot.

I'll go ahead and create a PR to package and push the helm charts, like shown in the Github Workflow. But my understanding is that we'll want to host this in the 'official' dapr public registry - correct @salaboy? Like as follows:

`helm repo add ambient https://dapr.github.io/helm-charts/`

If so, I'll need to get a better understanding of how to get write permissions to create and upload the helm chart package to that registry.

**Comment by salaboy** [comment]
@asarenkansah @mcruzdev we need to follow this workflow: https://github.com/dapr/dapr/blob/master/.github/workflows/dapr.yml

**Comment by salaboy** [comment]
Arthur created some of the credentials that we need to push the resources.. @mcruzdev @asarenkansah let me know if you can take a look on this.

**Comment by mcruzdev** [comment]
@salaboy I am available to add this one!

**Comment by asarenkansah** [comment]
Made a lot of progress today, but I need some help clarifying some key things.

My major concern is with the makefile. Ours is a lot different than how the official dapr repo has their’s setup. I can’t move much further until I get a better understanding on how different our workflows can be. What exactly do they expect to be constant?

More specifically, the following issues have been difficult to navigate:

The official dapr repo pushes their docker images through some markup kinda like a makefile does (haven’t seen this before). Do we need to create something that does the same? Or do we have freedom to deploy it differently?
The official dapr repo builds their artifact a lot differently as well view the following links in order to follow my logic:

- [Reference](https://github.com/dapr/dapr/blob/2371d2f44a606a8299f290599c95706658de88e2/.github/workflows/dapr.yml#L391) to the make release function in the github workflow

- [Reference](https://github.com/dapr/dapr/blob/2371d2f44a606a8299f290599c95706658de88e2/Makefile#LL289C2-L289C23) to the release call in the makefile

- [Reference](https://github.com/dapr/dapr/blob/2371d2f44a606a8299f290599c95706658de88e2/Makefile#L209) the the release archive function that is referenced in the release call in the makefile

We’ll need to build out our makefile quite a bit more if we need to mimic their deployment. It’d be easier to talk through all this on a zoom call if anyone’s open to that

**Comment by salaboy** [comment]
@asarenkansah great! 
ok.. so let me try to answer those questions: 
1) we just need to deploy a single image for the init-container.. so it should be much straight forward: https://github.com/dapr/dapr/blob/2371d2f44a606a8299f290599c95706658de88e2/docker/docker.mk#L167 like that 

2) For building is the same.. we just need to make sure that we create one binary for arm64 and one for amd64, but we don't need to build different binaries.. we just have one. 
Here for the release -> https://github.com/dapr/dapr/blob/2371d2f44a606a8299f290599c95706658de88e2/.github/workflows/dapr.yml#L582 I think the idea is to read the github release tag and from there find out which version of the artifacts to create.. We should do something like that.. so we can create releases and run the workflow on top of the github release.

**Comment by salaboy** [comment]
done in v0.0.10 I will create a separate issue for docs
